source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.2.2", ">= 7.2.2.1"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"
gem 'pg'
gem 'webrick'
gem 'rack', '2.2.10'

gem "tzinfo-data"

gem 'rufus-scheduler'
gem 'delayed_job_active_record'
gem 'sidekiq'

gem 'awesome_print'
gem 'prometheus-client'
gem 'diplomat'
gem 'redis'
gem 'connection_pool'
gem 'get_process_mem'
gem 'with_advisory_lock'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
end
