# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport'
gem 'rack'

gem 'puma', require: false
gem 'thin', require: false
gem 'passenger', require: false


#gem 'falcon', require: false

gem 'awesome_print'

  
